# Generated by Django 5.0 on 2023-12-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_sys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PRENOM',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='NOM',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='MATRICULE',
            new_name='matricule',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='SALAIRE_MENSUEL',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='payements',
            old_name='MATRICULE',
            new_name='matricule',
        ),
    ]
